export-help.py
frescobaldi_app/fileinfo.py
frescobaldi_app/ly/lex/__init__.py
frescobaldi_app/ly/musicxml/iter_mediator.py
frescobaldi_app/ly/musicxml/ly2xml_mediator.py
frescobaldi_app/ly/musicxml/lymus2musxml.py
frescobaldi_app/ly/musicxml/xml_objs.py
frescobaldi_app/objecteditor/widget.py
frescobaldi_app/qpopplerview/printer.py
frescobaldi_app/svgview/view.py
frescobaldi_app/vcs/gitrepo.py

Most of my Python 3 patches are not needed anymore. The remaining four patches are still needed.

Python3 stable

---

macosx/mac-app.py

See https://github.com/wbsoft/frescobaldi/pull/557#issuecomment-69078773.

fixes in mac-app.py

---

frescobaldi_app/convert_ly.py
macosx/mac-app.py

A comment change requested by Davide Liessi.
A fix in convert-ly error reporting - first result of running pylint on the frescobaldi code.

Two minor fixes

---

frescobaldi_app/documentmenu.py
frescobaldi_app/mainwindow.py
frescobaldi_app/midifile/song.py
frescobaldi_app/midiinput/widget.py
frescobaldi_app/objecteditor/defineoffset.py
frescobaldi_app/objecteditor/widget.py
frescobaldi_app/po/md2pot.py

Python 3 support is getting on par with Python 2. 2to3 is running out of real issues. I tested almost all menu items, and in many cases I would find some GUI ugliness rather than a Python 3 issue. I'm not a GUI designer, I just fixed simple things.

More Python 3 work, minor GUI changes

---

frescobaldi_app/engrave/lytools.py
frescobaldi_app/file_export/__init__.py
frescobaldi_app/layoutcontrol/color-voice.ily

I tested the code carefully, but I don't do much GUI programming, so I'm submitting this patch as a pull request.
As few stylistic questions about the code.
Would it be better to have a separate file for the audio export dialog? Or is the code too trivial for that?
Is it OK to do so many things in the constructor? Or should I move some of that stuff to another function? If so, should it be a slot or just a class method?
Any better ideas what to write in self.setMessage()?

Reimplement "Export Audio" using a dialog

---

frescobaldi_app/main.py

Monkey-patch some PyQt class methods to strip trailing NULLs.
Fixes #541 
---
Monkey-patching is generally bad, but we are just stripping NULLs that should not be there in the first place. The additional code is minimal and doesn't appear it time-critical paths.
Fixing every caller would be very intrusive.

Fix support for filenames with non-BMP characters on Python 2

---

frescobaldi_app/file_import/__init__.py
frescobaldi_app/mainwindow.py

An attempt at the drag and drop import.

Drag and drop import

---

frescobaldi_app/po/zh_CN.po

I will continuely translate zh_CN.po. Please merge the new po to master.

translated zh_CN.po to popplerprint.py

---

frescobaldi_app/snippet/insert.py

I got the idea of macro snippets, that is snippets that put together other snippets and also other Frescobaldi menu options.
For snippets the `name` variable has to be used both in the original snippet and in the macro.
For menu options I use the name of the action which is a bit awkward and not at all straight-forward from an user perspective. Perhaps a matching against the `action.text()` could be used instead.
Also it's perhaps a bit clumsy to collect the snippets and the actions here when they are already collected elsewhere...

Adding macro functionality for snippets

---

frescobaldi_app/autocomplete/analyzer.py

Add also support for drum mode

---

frescobaldi_app/search/__init__.py

issue #822 pressing ctrl+f generates exception

---

frescobaldi_app/po/es.po

Made against 3.x branch; maybe it is valid for 2.20 as well?

Spanish translation update.

---

ChangeLog
frescobaldi_app/po/cs.po
frescobaldi_app/po/de.po
frescobaldi_app/po/es.po
frescobaldi_app/po/fr.po
frescobaldi_app/po/frescobaldi.pot
frescobaldi_app/po/gl.po
frescobaldi_app/po/it.po
frescobaldi_app/po/nl.po
frescobaldi_app/po/pl.po
frescobaldi_app/po/pt_BR.po
frescobaldi_app/po/ru.po
frescobaldi_app/po/tr.po
frescobaldi_app/po/uk.po
frescobaldi_app/po/zh_CN.po
frescobaldi_app/po/zh_HK.po
frescobaldi_app/po/zh_TW.po
frescobaldi_app/search/__init__.py
frescobaldi_app/userguide/manuscriptview.md

Signed-off-by: Stefan Weil <sw@weilnetz.de>

Fix some typos (found by codespell)

---

frescobaldi_app/macosx/icon_drag_eventhandler.py
frescobaldi_app/qpopplerview/cache.py
frescobaldi_app/qpopplerview/magnifier.py
frescobaldi_app/qpopplerview/page.py

This resolves #816 (high DPI rendering on Mac Retina displays in music view) + some minor fixes. Only qpopplerview has been modified, not qpageview (replacement of qpopplerview in development).

Retinasupport in qpopplerview

---

frescobaldi_app/qpopplerview/view.py

Enable zoom using pinch gesture on trackpad (works at least under Mac OS X).

Feature: zoom with pinch gesture in popplerview

---

README-development

I'm not sure if I've caught everything properly

Update README-development to Python3/Qt5

---

frescobaldi_app/documentinfo.py
frescobaldi_app/preferences/general.py

This is my attempt to provide the function described in #872.
I add a new option in the preferences dialog, user can turn this function on and provide a template string to configure the way a new default filename is created.

Support custom default file name template

---

frescobaldi_app/mainwindow.py
frescobaldi_app/menu.py

Fixes #676
For now the default shortcut is Ctrl+Alt+G because Ctrl+G
is already taken

676: Add "Goto Line" command

---

frescobaldi_app/scorewiz/build.py
frescobaldi_app/scorewiz/settings.py

Score Wizard: Provide options for landscape/rotated

---

frescobaldi_app/po/zh_CN.po

As mentioned in #899, I tried to improve the Chinese(Simplified) translation of the GUI.
I completed many untranslated items and modified many translations to make them more conventional.
Most items of the GUI has been translated now. However, the user guide has not been translated yet. Also, there are some items that I can't come up with a good translation and are left untranslated. I wish someone could help.
For me, I hope this can close #899

Update Chinese(Simplified) translation

---

frescobaldi_app/file_import/abc.py

Added missing bracket

---

frescobaldi_app/po/pl.po

Update polish translation

---

frescobaldi_app/documentcontextmenu.py

Added a submenu for open documents in tab context menu

---

frescobaldi_app/midiinput/__init__.py
frescobaldi_app/midiinput/widget.py

Fix issue #866.
This PR takes the contribution from @deviskra in PR #1039 and adapt it to master branch/python 3.

Adding a "replace mode" to MIDI Input

---

i18n/it/frescobaldi.po
i18n/it/userguide.po

@dliessi
Parliamo pure in italiano per discutere della traduzione.
Ho un paio di dubbi:
- meta information = metainformazioni
Non credo sia una parola italiana ma non mi è venuto in mente molto altro.
*metadati* non mi sembra corretto in questo caso.
- Can't pop job from non-started Job Queue
Credo che pop sia un termine tecnico ben preciso, come è descritto [qui](https://en.wikipedia.org/wiki/Stack_(abstract_data_type)).
Ma non sono affatto sicuro di averlo tradotto correttamente.

Update italian translation

---

i18n/frescobaldi/cs.po

Czech translation update of cs.po file. Greetings.

Czech translation update

---

frescobaldi_app/logtool/errors.py

Fix off-by-one when jumping from log to LilyPond code

---

frescobaldi_app/portmidi/__init__.py
windows/freeze.py

imp is planned to be removed in Python 3.12.
Fixes #1457

Deal with imp deprecation

---

frescobaldi_app/layoutcontrol/color-directions.ily
frescobaldi_app/layoutcontrol/color-voice.ily
frescobaldi_app/layoutcontrol/color-voices.ily
frescobaldi_app/layoutcontrol/debug-layout-options.ly
frescobaldi_app/layoutcontrol/display-grob-anchors.ily
frescobaldi_app/layoutcontrol/display-grob-names.ily
frescobaldi_app/layoutcontrol/info-paper-columns.ily

Also fix a few things.
Tested with LilyPond 2.18.2, 2.22.2 and current master.

Make all layout control options compatible with LilyPond 2.23

---

frescobaldi_app/outline/widget.py
frescobaldi_app/userguide/outline_configure.md
frescobaldi_app/userguide/prefs_general.md

- Add selection mark in outline widget
- Update userguide

Small revision after outline fix

---

frescobaldi_app/autocomplete/completiondata.py

Autocomplete: add unfoldRepeats

---

README.md

Add note about maintenance to README.md

---

frescobaldi_app/fonts/textfonts.py

Use the current regular expression API in update_filter()

---

frescobaldi_app/preferences/tools.py

Center preferences outline patterns edit widget in the tools window.

---

frescobaldi_app/i18n/qtranslator.py
i18n/frescobaldi/it.po
i18n/messages.py

Add new Qt strings to be translated

---

i18n/mo-gen.py
i18n/po-update.py

Rename frescobaldi_app under i18n/ directory

---

.github/workflows/release.yml
CHANGELOG.md

This is what was missing for the 4.0.0 release.
Let's see if the Action will complete successfully. I guess I'll have to do some trial and error...
Fixes #1584 and #1618

Sign macOS app

---

CHANGELOG.md
frescobaldi/userguide/credits.md
linux/org.frescobaldi.Frescobaldi.metainfo.xml.in

4.0.0 release

---

.github/workflows/release.yml
pyproject.toml

Project name should be lowercase.
This completes the work started in #1906.
I've already verified that the workflow run successfully.

workflow: set version dynamically

---

frescobaldi/midiinput/__init__.py

Fix #853
Honestly, I don't have much understanding of the code but at a first glance it may just be a typo. I would appreciate a review from a programmer :-)
I can only say that it works.
Thanks to @drydh for his analysis in #853.

Make MIDI input work again on Windows >=10

---

frescobaldi/preferences/musicviewers.py
frescobaldi/preferences/tools.py

This was requested in #1413. My thought was to get the functionality in place first, then tweak the design as part of #1414.
Edit: I originally cited #1927 but it looks like #1413 requested it first.

Add music view defaults in the Preferences dialog

---

frescobaldi/preferences/__init__.py
frescobaldi/preferences/general.py
frescobaldi/preferences/musicviewers.py
frescobaldi/userguide/getstarted.md
frescobaldi/userguide/preferences.md
frescobaldi/userguide/prefs_general.md
frescobaldi/userguide/prefs_helpers.md
frescobaldi/userguide/prefs_musicviewers.md

Reorganize Preferences

---

CHANGELOG.md
frescobaldi/appinfo.py
linux/org.frescobaldi.Frescobaldi.metainfo.xml.in
pyproject.toml

I'll make the release tomorrow

4.0.2 release

---

frescobaldi/macos/globalmenu.py

in commit 71c9d43e3d8b27dfa45705a311a8e5c5649aaea9
Fix #1968

importMusicXML was renamed import_musicxml

---

i18n/frescobaldi/ja.po

I'm sorry that I really screwed up my ja-update branch and inadvertently deleted ja-update branch on github. Hence, PR #1962 had been closed. I'm creating a new PR.

Japanese update

---

frescobaldi/app.py
frescobaldi/debug.py
frescobaldi/extensions/__init__.py
frescobaldi/externalchanges/widget.py
frescobaldi/job/__init__.py
frescobaldi/midiinput/__init__.py
frescobaldi/preferences/extensions.py
frescobaldi/scorewiz/build.py
frescobaldi/snippet/insert.py
frescobaldi/vcs/__init__.py
frescobaldi/viewers/__init__.py
frescobaldi/widgets/keysequencewidget.py
pyproject.toml

See the initial list in
https://github.com/frescobaldi/frescobaldi/issues/1525#issuecomment-2942947872
I've started working on the easier errors with the smaller number of occurences.
To complete this PR I think I'll give a deeper look into these ones in the next days:
```
2	E722	[ ] bare-except
2	F403	[ ] undefined-local-with-import-star
1	F402	[ ] import-shadowed-by-loop-var
```

Fix E401,E701,E711,E712,E721,F402,F403,F821 errors found by ruff

---

frescobaldi/viewmanager.py

Fix a call to an obsolete method in the ViewManager event handler

---

frescobaldi/userguide/credits.md

Credits: mark untranslatable strings consistently

---

frescobaldi/preferences/musicviewers.py
pyproject.toml

to Grid Layout, which better describes its function.
Fix #1953

Rename the Raster page layout in Preferences

---

i18n/frescobaldi/ja.po
i18n/userguide/ja.po

For #2027 and qpageview 1.0.1 release.

Update Japanese translation

---

frescobaldi/widgets/restartmessage.py
i18n/frescobaldi/it.po
i18n/userguide/it.po

Fix a i18n string + Italian translation update

---

frescobaldi/fonts/musicfonts.py

Fix a TypeError in MusicFontsModel.check_type()
