frescobaldi/frescobaldi

frescobaldi_app/pitch/pitch.py

The key has to be lower case, so the dialog should propose it right.
And I think "e.g." is more appropriate than "i.e." here.

Fix typo in mode shift dialog

---

frescobaldi_app/vcs/gitrepo.py

Close git config file on exit from _read_config()

---

frescobaldi_app/autocomplete/documentdata.py
frescobaldi_app/docbrowser/sourceviewer.py
frescobaldi_app/hyphenator.py
frescobaldi_app/hyphendialog.py
frescobaldi_app/install/update.py
frescobaldi_app/ly/dom.py
frescobaldi_app/preferences/fontscolors.py
frescobaldi_app/preferences/shortcuts.py
frescobaldi_app/slexer.py
frescobaldi_app/widgets/charmap.py
macosx/mac-app.py

Python 3 doesn't understand `unichr` and `unicode`. I tend to use the approach where we code for Python 3 and make Python 2 "thoroughly-unicodized" using try-except construct. Thanks to separate namespaces, such tricks don't affect other modules.
The output of hyphenator has be greatly improved. It can deal with non-latin encodings on the command line.
python3 hyphenator.py /home/proskin/src/frescobaldi/frescobaldi_app/hyphdicts/hyph_ru_RU.dic попарнопротивопоставленные
попарнопротивопоставленны – е
попарнопротивопоставлен – ные
попарнопротивопостав – ленные
попарнопротивопо – ставленные
попарнопротиво – поставленные
попарнопроти – вопоставленные
попарнопро – тивопоставленные
попарно – противопоставленные
попар – нопротивопоставленные
по – парнопротивопоставленные
python3 hyphenator.py …

Eliminating unichr

---

freeze.py
frescobaldi_app/charmap/widget.py
frescobaldi_app/file_import/__init__.py
frescobaldi_app/file_import/musicxml.py
frescobaldi_app/po/mofile.py
frescobaldi_app/po/molint.py
frescobaldi_app/po/setup.py

We have two places where all exceptions related to language files are silently ignored. That's wrong. The robustness principle says: "Be conservative in what you do, be liberal in what you accept from others". Language files is what we do, even if translations are done by third parties.
Removing those exception handlers immediately exposed problems in *.mo header handling in Python 3. They have been fixed, including functions called by molint.py. The later was also failing to close *.mo files.
The visible result is that plural forms work with Russian translation under Python 3 now (at the moment, they are only used when exporting snippets).
Tabs used for code indentation cause exceptions in Python 3. I've replaced them with spaces using formatting suggested by autopep8.

Plural forms working in Python 3

---

frescobaldi_app/file_import/musicxml.py
frescobaldi_app/ly/musicxml/create_musicxml.py

Both commits involve changing files from text to binary mode. Text mode is may be convenient to read ASCII-only output. It may be a good choice for the code that only runs in Python 2 or Python 3. But if we want to support both versions of Python and deal with non-ASCII data (such as a non-latin filename in error output). Text files deal with different types on Python 2 and Python 3, even though both are called "str". Python 3 does the encoding/decoding for us, Python 2 doesn't. That's too much trouble and too little control over the encoding.
Another case of unclosed file has been caught. Python 3 is good at catching such errors.

Python 3 issues with MusicXML import/export

---

frescobaldi_app/portmidi/__init__.py
frescobaldi_app/vcs/gitrepo.py

I tried Frescobaldi on Windows under ActivePython 2.7.8.10. There were two fatal problems: pypm.Initialize() was missing and there was no "remote" section in .git/config - git for Windows forgot to create it. It turns out "import pypm" imports "PyPM", an ActiveState package manager. I used a simple hasattr() trick to reject it.
As for git, I was tired of errors due to .git/config, so I completely eliminated parsing that file. "git config" provides all that functionality and it's documented. While at that, I fixed running git in shell and disallowed passing strings as arguments - only lists are allowed now. Finally, STGit branches are fully hidden from view now. They don't contain the source tree; checking them out would remove the sources.

Windows fixes and git robustness

---

freeze.py
frescobaldi-wininst.py
frescobaldi_app/preferences/import_export.py
frescobaldi_app/snippet/import_export.py
frescobaldi_app/userguide/util.py
macosx/build-dmg.sh
macosx/mac-app.py

Renaming modules is hard, but this one was needed. There are many "info" variables around the source, it was confusing to have a module of the same name.
Some references to info.py were left after your patch. Some were found with regexes, some were found by pylint, some were found accidentally. I hope I didn't miss anything.

More changes needed after renaming info.py to appinfo.py

---

frescobaldi_app/debug.py

If we can assume a setup where python-ly and frescobaldi are next to each other in a directory, this will facilitate debugging latest version of both packages.

Adding assumed path to python-ly as mentioned in issue #592

---

frescobaldi_app/qpopplerview/magnifier.py

Don't define `__eq__` for class Magnifier, it becomes unhashable. Rename
`__eq__` to `same_page`, check that its argument is not None.
---
I want it to be reviewed.
python3 passes None to `__eq__`, which causes a traceback:
```
Traceback (most recent call last):
File "/home/proskin/src/frescobaldi/frescobaldi_app/qpopplerview/magnifier.py", line 84, in paintEvent
if newPage != self._page:
File "/home/proskin/src/frescobaldi/frescobaldi_app/qpopplerview/magnifier.py", line 126, in __eq__
self._document() == other._document() and
AttributeError: 'NoneType' object has no attribute '_document'
```
python2 doesn't do that, it evaluates comparisons to None as False on its own. But simply adding protection against None is not enough. Python 3 gives another traceback:
```
Traceback (most recent …
```

Fix traceback on magnifier use in Python 3

---

frescobaldi_app/file_import/__init__.py
frescobaldi_app/file_import/abc.py
frescobaldi_app/file_import/midi.py
frescobaldi_app/file_import/musicxml.py
frescobaldi_app/file_import/toly_dialog.py
frescobaldi_app/menu.py

The code is restructured with a generic import dialog, and abc2ly and midi2ly imports are added.
Some issues remaining:
1. abc2ly doesn't work in the same way as musicxml2ly and midi2ly.
2. The previous dialog has to be "forgotten" when switching between different imports.
I've indicated the problematic places in the code.

Adding abc2ly and midi2ly imports

---

frescobaldi_app/remote/api.py

Fixes #650 
`_incoming_handlers` doesn't seem to be used for anything. Use it as a flag whether `socket.deleteLater()` has been called.

Handle two calls to incoming.close(), one for disconect, one for "bye"

---

frescobaldi_app/manuscript/widget.py

For now the manuscript viewer can only handle a single PDF
(and I think it's a good idea to leave it at that for now).
Therefore the the file open dialog should only allow opening one file,
and as we can only open PDFs for now this should also be restricted.
Once we open up the tool it'll be easy to re-add the functionality.

Make manuscript viewer open single file (pdf) only

---

frescobaldi_app/highlight2html.py
frescobaldi_app/mainwindow.py
frescobaldi_app/preferences/editor.py
frescobaldi_app/userguide/prefs_editor.md
frescobaldi_app/viewhighlighter.py

I hope this really works and there are no other "side-effects" that I didn't see/realize.
This adds some more options to the source export that I have always missed (actually I had to manually replace output for each export).
This PR relies on https://github.com/wbsoft/python-ly/pull/42 against `python-ly`. That means it can only be tested when the other PR has been merged or with the `config-colorize` branch of `python-ly` checked out.

Source export options

---

frescobaldi_app/userguide/prefs_lilydoc.md

Some people think that they can add whatever URL taken from the LilyPond website, but it seems that a specific format should be used instead:
- [on lilypond-user](https://lists.gnu.org/archive/html/lilypond-user/2015-11/msg00252.html)
- issue #534 
lilypond.org is down since a few days, but you can check the redirects [here](http://git.savannah.gnu.org/gitweb/?p=lilypond.git;a=blob;f=Documentation/web/server/lilypond.org.htaccess;h=c6da26a1bb1ac2d54cd91f32baacc1a6459e1927;hb=HEAD#l52).

userguide: explain how to add URLs pointing to lilypond.org documentation

---

frescobaldi_app/scorewiz/scoreproperties.py
frescobaldi_app/scorewiz/settings.py

This commit introduces a checkbox underneath the tap tempo widget in the score wizard. This checkbox is labelled "Round tap tempo value" and allows the user to enter a very precise tempo using the tap tempo button.
When the checkbox is set (default value for newer versions of Frescobaldi), behaviour is not changed, however when it is turned off, the tempo entry box will show the raw tempo from the button. For example, if the user tapped at exactly 117 BPM, the value shown will not be rounded to 116, i.e. one of the values in the tempo box.
This modification is a request from a friend, @pl-gauthier.

Round tap tempo value to nearest common tempo

---

frescobaldi_app/debuginfo.py

The pull request is based on v2.x because I currently cannot run Qt5, but the changes are independent of Qt, so they can be easily cherry-picked in master branch.
@wbsoft Can you apply the changes to both branches or would you prefer me to apply them also to master, even if I cannot test it?

add kind of Mac installation to debuginfo (fixes #785)

---

ChangeLog

Remove conflict marker added in commit 0b80a60 ("Merge remote-tracking
branch 'origin/master' into manuscript-viewer", 2016-03-11).

ChangeLog: Remove stray Git conflict marker

---

frescobaldi_app/midihub.py
frescobaldi_app/midiinput/__init__.py
frescobaldi_app/midiinput/elements.py

Could fix issues #797 and #853.
- midiinput/__init__.py used "midi/input_port" and preferences used "midi/midi/input_port".
- Bug has existed since first implementation of midi-input in commit 9473aa87 (2013-11-12).

BUGFIX: MIDI Input setting was never used!

---

frescobaldi_app/file_export/__init__.py

This is functionality that has already been available with python-ly
but simply not "activated" in Frescobaldi.
Closes #873
I hope this is sufficient as it simply passes the filename of the
currently open tab. If anything like respecting master documents
should be respected some more work would be involved (but actually
I don't think that should prevent this from being merged).
**NOTE:** I have tested this on the `2.19` branch but I don't think there should be any issue applying it to current master as well.

Allow MusicXML export to follow \include's

---

frescobaldi_app/midiinput/tool.py
frescobaldi_app/midiinput/widget.py

Added a keyboard shortcut for switching between accidental styles (flats or sharps), requested in Issue #890. I've kept the default shortcut to be Ctrl+Shift+3 and icon transpose-tools.svg.

Keyboard shortcut for Midi input accidentals

---

frescobaldi_app/widgets/listedit.py

The design of the slot handlers prevented them to be overridden.
If a subclass reimplemented them, *both* were connected to the signal.
This commit makes the handlers more traditional, and now subclasses
can easily override each of the handlers.

widgets.listedit: Make button slots more traditional

---

frescobaldi_app/engrave/command.py
frescobaldi_app/engrave/custom.py
frescobaldi_app/lilypondinfo.py

This will fix a long-standing annoyance - but is only implemented with downloaded and self-compiled versions on Linux. I assume distro packages will work as well (or don't need it anyway), but I have no idea about Mac and Win. Maybe the problem doesn't apply to them, but I want to wait for feedback on that before merging this PR.
Not adding this can cause compilation failures when the bundled versions of libraries (like Ghostscript) don't match the system-provided ones.

Add library path to LilyPond invocation

---

ChangeLog
frescobaldi_app/engrave/custom.py

This is a preliminary Pull Request to have people test the feature and discuss before finishing it.
Addresses #724
Adds an entry "First System Only" to the "Engraving Mode" combo in the Engrave (Custom) dialog.
Please test and discuss the naming conventions used.
**Missing:** The compiled preview is *not* displayed in the Music View and only available through `LilyPond=>Generated Files`. A quick look into the code didn't tell me how to fix that as well.

WIP: Add "First system only" option to Engrave (Custom)

---

frescobaldi

Trying to package version 3.0.0 for fedora, I got an error because the launch script references python which executes python 2 by default.

Update launch script for python 3

---

frescobaldi_app/open_file_at_cursor.py
frescobaldi_app/view.py

I write this new version.
A user will get a tooltip displaying the exact path of a include file when the mouse is hovering near the include file with the Ctrl button pressed. 
For invalid files it will display "This is an invalid include file"

Add Ctrl + mouse hovering to display tooltips for include files

---

frescobaldi_app/vcs/gitjob.py
frescobaldi_app/vcs/gitrepoo.py

This refers to my comment https://github.com/wbsoft/frescobaldi/pull/974#issuecomment-311201492
Git() is now a more straightforward object responsible for synchronously
or asynchronously running a single Git command.
The asynchronous behaviour relies completely on Qt-style signalling,
i.e. there are no callback functions but the option to connect to signals.
The class forwards all the signals from QProcess.
I have removed the queue concept (although it was well implemented). If we need it at all we should move the idea to the `Repo()` object but keep the `Git()` object clean and focused.
Maybe we don't need a queue at all because the same effect may be achieved using signals and slots (call Git command A and connect to a slot. In that slot call Git command B etc.)
---
This code will *not* …

WIP: Rewrite gitjob.Git() as a single-job class using Qt-style signals

---

frescobaldi_app/sessions/menu.py

This commit parses session names for (one) slash in it and treats such
sessions as grouped sessions and creates submenus for each.
The image also shows that the current session is within the `Group` submenu

Submenus for grouping sessions in Sessions menu

---

frescobaldi_app/po/it.po

fixing typo in it language

---

frescobaldi_app/doclist/widget.py
frescobaldi_app/documentmenu.py
frescobaldi_app/tabbar.py
frescobaldi_app/util.py

Adds the tooltip to the Documents menu that is also found in the Documents Tool and the editor's tabs.
Merges duplicate implementation to a common function in the `util` module.

Add file path as tooltip in Documents menu

---

frescobaldi_app/main.py

With the -p or --python-ly option the path to python-ly can be specified.
This maybe makes it cleaner to use python-ly from the Git repository
(rather than wrapping the call to Python with a PYTHONPATH= clause).
This is inspired by the recent discussion about installation instructions.

Add -p/--python-ly command line option

---

frescobaldi_app/app.py
frescobaldi_app/debug.py
frescobaldi_app/hyphenator.py
frescobaldi_app/language_names/generate.py
frescobaldi_app/lydocinfo.py
frescobaldi_app/lydocument.py
frescobaldi_app/mainwindow.py
frescobaldi_app/midifile/parser.py
frescobaldi_app/musicview/pointandclick.py
frescobaldi_app/musicview/widget.py
frescobaldi_app/objecteditor/widget.py
frescobaldi_app/po/qtranslator.py
frescobaldi_app/progress.py
frescobaldi_app/quickinsert/buttongroup.py
frescobaldi_app/simplestate.py
frescobaldi_app/svgview/view.py
frescobaldi_app/userguide/whatsthis.py
frescobaldi_app/vcs/test.py
frescobaldi_app/viewers/pointandclick.py
frescobaldi_app/viewers/popplerwidget.py
macosx/mac-app.py
windows/freeze.py
windows/frescobaldi-wininst.py

Closes #1003
It seems these `__future__` imports are all obsolete by now since Python2 isn't supported anymore.
(For reference: Has been done through `for file in $(find . -iname "*.py"); do sed -i 's/from __future__.*//g' $file; done`)

Remove all __future__ imports

---

frescobaldi_app/icons/Audio-x-generic.svg
frescobaldi_app/icons/music-directions.ly
frescobaldi_app/icons/music-directions.svg
frescobaldi_app/menu.py
frescobaldi_app/panelmanager.py

The Tools menu is becoming too long IMO, so I think we should introduce additional submenus, even if that requires one more level to access some options. This PR introduces the following changes:
* New "Code Formatting" submenu with reformat, indent etc.  
I have some ideas to add more "linting" commands that would further extend that list of commands, which is an additional incentive to move them in a submenu
* Submenus for Tools Panels
To be discussed:
* Naming of the panels submenus
* organization of panels in these submenus
* should the remaining tools also be moved to submenus, if so, what should they be called like
* If that is accepted the mnemonics for the panels can be reconsidered because they have to be unique only in their submenus
* Should the section from "Pitch" to "Quick …

Restructure Tools Menu

---

frescobaldi_app/engrave/command.py

Closes #1094
It seems LilyPond on Windows requires a trailing slash while Linux
doesn't care about this.
I don't know about Mac, though, so the PR should be tested on Mac
before that.

Ensure includepaths have trailing slashes

---

frescobaldi_app/engrave/custom.py
frescobaldi_app/file_import/__init__.py
frescobaldi_app/file_import/abc.py
frescobaldi_app/file_import/midi.py
frescobaldi_app/file_import/musicxml.py
frescobaldi_app/file_import/toly_dialog.py
frescobaldi_app/job/__init__.py
frescobaldi_app/job/dialog.py
frescobaldi_app/job/lilypond.py
frescobaldi_app/menu.py

This closes #1105, but not only by removing the limitation to the import timeout but by a complete review of the way file imports are structured.
In terms of implementation much redundancy has been removed and the code streamlined.
For the user interface external imports are now displayed with the help of a (new) dialog running external jobs and displaying the logs.
Additionally the import now fails properly when the underlying import script fails (previously a truncated `.ly` file had been produced without giving any warning).

#1105: Fix external file import

---

frescobaldi_app/log.py

Closes #1066
There seems to be a conflict between letting the log font be zoomed
and respecting the Preference for font size.
So this makes the Log Tool consistent with how font sizes are managed
in the document editor. But the ability to *zoom* the log with the
mouse or keyboard shortcuts (?) is removed by that commit.
@mmeyn

#1066: Respect Logtool font size setting

---

frescobaldi_app/panelmanager.py

This function is helpful to access any panels from anywhere else.
I think it is pretty lightweight - except if there's another way already present that I didn't see.
(relates to #1090)
Usage example:
```python
import panelmanager
manuscript_viewer = panelmanager.manager().panel_by_name('manuscript')
```

PanelManager: Add panel_by_name() function

---

frescobaldi_app/icons/Tango/scalable/go-jump-back.svg

This is a flipped version of go-jump.svg
@wbsoft where do these icons in `Tango` and `TangoExt` come from? Is it appropriate to add icons into these folders (if they are derived like in the current case), or should they be put directly in the `icons` directory to the other custom icons?

Add go-jump-back icon

---

ChangeLog
frescobaldi
frescobaldi_app/app.py
frescobaldi_app/main.py
frescobaldi_app/midifile/parser.py
frescobaldi_app/snippet/insert.py

I stumbled over [`main.patch_pyqt`](https://github.com/wbsoft/frescobaldi/blob/master/frescobaldi_app/main.py#L115-L147) and think this can/should be dropped. Essentially this was necessary for Python2 and should *not* be necessary for Python3 anymore.
Based on the code in the function this "patch" was necessary until Python 3.2, but given the fact that Python 3.3 was released in 2013 and has "reached end-of-life" (see https://www.python.org/download/releases/3.3.3/) I think it's safe to drop it altogether and bump the requirement to Python 3.3.
This is also related to #1126.
I'm pretty sure there's no problem with this but wanted to ask for feedback anyway.

Require Python 3.3

---

frescobaldi_app/widgets/completer.py

#1088 describes how the fact that entering a dot makes editing harder
in cases when there is no completion intended (`\tweak Beam.` should
*not* complete to `beam-thickness`)
This commit removes the link from Enter/Return to `.`. That means that
entering the dot will *not* automatically complete to the first match
in the completer popup. If that is wanted one would now have to enter
ENTER plus the dot. This need for one more keystroke seems more than
worth it, considering less unintended completions.

#1088 Autocompleter: Don't treat dot like ENTER

---

frescobaldi_app/extensions/__init__.py

https://stackoverflow.com/questions/37066961/pyqt4-saving-list-to-qsettings
indicates I had made a mistake by setting the default type to "list" instead
of the type "str" for the contained elements.
For some reason this did not break on Linux but only on Windows.
This *should* fix #1137

#1137: Fix (?) setting empty default list for inactive extensions

---

frescobaldi_app/main.py

When running without python-ly installed, python throws an error: NameError: name 'ly_required' is not defined in main on line 145. Changing ly_required to appinfo.required_python_ly_version fixes this error.

Fix python-ly error message bug

---

frescobaldi_app/icons/__init__.py

Closes #1158
Frescobaldi was looking for icons in the "current theme",
which is the desktop environment's theme. So if the theme
selected in the preferences is not "default" the icons will
not be looked up from the theme that is active in Frescobaldi,
which is improved in this commit.
@wbsoft: This is a WIP commit because the icons are *not*
updated immediately upon the settings change but only after
a restart. All widgets with icons have to be called to redraw
their icons, and I'm not sure whether there's a generic way
to do so, or if we have to provide that functionality in all
widgets/actions that use icons individually.

Change icon theme along with GUI theme

---

frescobaldi_app/musicview/__init__.py

> it can zoom up to 6400% (vs previous 800%);
I hadn't noticed this before reading the comment.
Since the new qpageview can zoom up to 6400%
it is necessary to provide that value in the comboboxes too
(otherwise users wouldn't realize that feature).
The actual list in this commit is just a suggestion, though

Change default zoom levels

---

frescobaldi_app/preferences/musicviewers.py

I was initially confused by the two "Arthur" check boxes because I didn't know what "Arthur" is.
I think many users will *not* see the ToolTip, and even fewer will read the userguide page, so I suggest making it clear right in the UI.

Clarify "Arthur" labels in Preferences

---

frescobaldi_app/viewers/popplerwidget.py

I'm not sure whether this is the ultimate fix,
but I haven't seen any of these crashes anymore:
```
Traceback (most recent call last):
File
"/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/sessions/menu.py",
line 115, in slotSessionsAction
manager.get(self.parentWidget()).startSession(action.objectName())
File
"/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/sessions/manager.py",
line 90, in startSession
active = sessions.loadSession(name)
File
"/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/sessions/__init__.py",
line 115, in loadSession
setCurrentSession(name)
File
"/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/sessions/__init__.py",
line 157, in setCurrentSession
app.sessionChanged(name)
File "/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/signals.py", …
```

Fix crashes when changing sessions

---

frescobaldi_app/app.py

With this fix, Arthur can be used by Windows. This basically appends the normally used command line parameter to the args vector which is read by QApplication.
The parameter normally only applies to windows, but to make sure I would like to have this tested in a Linux and Mac version before mergin it to master.

Fix for using Arthur for Windows

---

frescobaldi_app/install/__init__.py
frescobaldi_app/install/update.py
frescobaldi_app/pagedview.py
frescobaldi_app/preferences/musicviewers.py

While testing this change, I had to run Frescobaldi twice for the install module to do its job.
Maybe before merging we should find out why that's happening.
How does it behave on Linux and Windows?

move arthurbackend_print preference to printing group

---

ChangeLog
frescobaldi_app/convert_ly.py
frescobaldi_app/file_import/toly_dialog.py
frescobaldi_app/lilychooser.py
frescobaldi_app/lilypondinfo.py
frescobaldi_app/macosx/__init__.py

I prefer this to be reviewed, since it is not trivial and does not touch only Mac-specific parts.
To test the new behaviour, you can artificially make `lilypondinfo.toolcommand` return `None` for some combinations of tool command and LilyPond version: the corresponding LilyPond entries should disappear from the list of the tool command.
You can also test with `lilypondinfo.toolcommand` always returning `None`, to see that it does not crash.

Fix Python selection on Mac

---

frescobaldi_app/mainwindow.py

The option of nesting dock areas is useful on large screens.
However, this would be good to be accompanied by a solution to #1321. When switching back to my significantly smaller laptop screen the layout is totally messed up.
This screenshot is not what I really want it to look like but demonstrates what is possible with this PR:
The editor still is the main widget of the window. There's nothing in the top dock area but the left and right columns are heavily nested. Note in the music/SVG view that combining docks in tabs is still possible.

Allow nested docks

---

frescobaldi_app/widgets/listedit.py

This is a convenience function to set the file mode of the included `QFileDialog`.
FilePathEdits may not only be useful for choosing directories.
I chose to add the option to pass in the value as a simple string so the caller doesn't have to include `QFileDialog`

Let FilePathEdit choose not only directories

---

frescobaldi_app/main.py

While this is addressing a Windows-specific issue, the added logic should work on all platforms. As such, I have omitted an OS check in the code. Unfortunately, I am unable to test on Mac or Linux, so we would need to confirm this does not introduce any new problems before merging the PR.
The underlying issue is that `QApplication` unintentionally mangles the argument list that it gets passed due to differences in string handling. There was logic added to use `os.fsencode` but no corresponding call to `os.fsdecode` was present to reconstitute the arguments.

Fixes #1379: Add explicit decoding of arguments.

---

frescobaldi_app/convert_ly.py
frescobaldi_app/engrave/custom.py
frescobaldi_app/job/lilypond.py

In "Run LilyPond with English messages" mode, Frescobaldi used to set
the LC_ALL and LANG environment variable for the LilyPond process.
With versions of LilyPond that use Guile 2 (2.23.7 and later, 2.23.6
for some, also 2.22 from Homebrew), this breaks compiling files with
non-ASCII characters because unlike Guile 1, Guile 2 actually decodes
the filename string from the command line, and does so based on the
locale encoding.  Fix this by only setting LC_MESSAGES, which is
enough to stop localization of log messages without messing with the
encoding used to decode command line arguments.

Fix compiling source files with non-ASCII characters with LilyPond 2.23.6+

---

frescobaldi_app/open_file_at_cursor.py

Fixes the warning
home/jean/repos/frescobaldi/frescobaldi_app/open_file_at_cursor.py:36: DeprecationWarning: invalid escape sequence '\s'
incl_regex = re.compile('(\\\\include\s*\")(.*)(\")')

Fix invalid escape sequence

---

frescobaldi

Most users won't see them due to Frescobaldi's GUI nature, but Frescobaldi contributors now will. These warnings would have provided an advance notice for things like the float conversion issues that plagued Frescobaldi in Python 3.10.

Enable Python warnings

---

frescobaldi_app/documentinfo.py

Unconditionally add directory of current LilyPond file to LilyPond
include directory list (-I ...) if engraving an unsaved file.
This enables use of relative paths in commands like \markup\epsfile ...
even if no actual \includes are being used in the .ly file.

Fix engraving of unsaved files using relative pathnames without \include

---

frescobaldi_app/documentstructure.py
frescobaldi_app/preferences/tools.py

This PR can be seen as a start of a more ambitious project to rewrite the structure code with the help of ly as a code parser instead of relying on regex. It's by necessity a little hacky to adapt to the overall implementation.

fix #1081: Ignore inactive code in structure

---

frescobaldi_app/portmidi/__init__.py
windows/freeze.py

[Redux of the broken and reverted commit https://github.com/Jean-Abou-Samra/frescobaldi/commit/0b05972c05386239843dbd62a1fae1a5cb763be4.]
imp is planned to be removed in Python 3.12.
The change in portmidi/__init__.py is inspired from
https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly
Fixes https://github.com/frescobaldi/frescobaldi/issues/1457

Deal with imp deprecation (redux)

---

frescobaldi_app/preferences/documentation.py

/doc/stable and /doc/latest are enough, as long as the redirects are promptly updated by the LilyPond team when a new stable is released.
<hr>
This is an easy patch. I'll merge it in a couple of days if there are no objections.

Do not suggest very old LilyPond version manual

---

README.md

Japanese has been added at the last of "Translated into:...". I'm not sure about the appropriate order of the languages.

Tiny update in README.md

---

frescobaldi_app/appinfo.py
frescobaldi_app/lilydoc/manager.py
frescobaldi_app/userguide/prefs_lilydoc.md

Set default remote URLs to browse LilyPond documentation

---

CHANGELOG.md
README-development
macosx/appdmg/appdmg.json
macosx/build-dmg.sh

Format based on keepachangelog.com
This is just a WIP and I look forward to your feedback.
The markdown format renders much better than plain text IMO and it makes possible to use links to specific release notes, see the anchors here:
https://github.com/fedelibre/frescobaldi/blob/changelog/CHANGELOG.md
I may copy the contents of the old ChangeLog, if we agree that this format is better.

Add a new changelog file in Markdown format

---

frescobaldi_app/convert_ly.py
frescobaldi_app/file_import/toly_dialog.py

Application bundles overwrite several environment variables. In particular they (at least those generated by py2app) define PYTHONPATH and PYTHONHOME to the Resource directory inside the bundle, breaking the Python module search.
This PR should fix #1395.

fix running Python tools from app bundle on Mac

---

CHANGELOG.md
README-development
frescobaldi_app/appinfo.py
frescobaldi_app/userguide/credits.md
linux/org.frescobaldi.Frescobaldi.metainfo.xml.in

I set 21st of March as a target release date. We thought that 3.3.0 would have come out last Christmas and instead we had to wait for Spring! :-)
Please check if I missed anything.
I didn't dare to update the `credits.md` file, but I'm sure that Jean should be put there. @jeanas feel free to add yourself there and describe what you did; you can add a commit on top of mine.
I've added @19joho66 who usually makes the Windows package.

Release Frescobaldi 3.3.0

---

frescobaldi_app/engrave/custom.py

I've noticed this typo while running LilyPond in custom mode using the "first system only" option.
And I saw in the log:
> warning: no such internal option: no-print_pages
I don't know if it's ever been print_pages. I guess it was a typo.

Fix misspelled LilyPond option

---

frescobaldi_app/musicview/contextmenu.py

How to replicate the issue:
- open any document whose pdf contains a link (e.g. any document using the unmodified default layout has a link to the LilyPond homepage in the tagline)
- right-click the link
- from the context menu select either "Open Link in New Window" or "Copy Link" (both actions are affected)
- instead of performing the selected action the editor presents a crash report window
(The issue seems to be around since about c5ed67151.)

musicview: fix crash in link context menu

---

linux/org.frescobaldi.Frescobaldi.metainfo.xml.in

This tag is required to pass Flathub validation and publish new versions on Flathub.
As developer name I chose "Frescobaldi project".
Wilbert is the original author of course, but in this case I think we want to show who is actively developing and maintaining Frescobaldi.

Add a tag required by Flathub validation

---

frescobaldi_app/appinfo.py

Currently, a warning is generated. According to the docs (and this warning), the
`QGuiApplication::desktopFileName` should be called without the `.desktop`
extension.
https://doc.qt.io/qt-6/qguiapplication.html#desktopFileName-prop

Fix string that is passed to setDesktopFilename

---

frescobaldi_app/debuginfo.py
frescobaldi_app/userguide/credits.md

Two trivial fixes to re-alphabetize names and remove references to Poppler in the About box/credits.

Qt6 credit fixes

---

frescobaldi_app/textedit.py

This fixes a bug reported in frescobaldi/qpageview#30 where point-and-click fails when the filename contains both punctuation and non-latin1 characters.

Use urllib to unquote textedit URLs

---

frescobaldi_app/copy2image.py

This PR changes the copy to image dialog to always use PNG as discussed under #1811.
I also increased the default copy resolution to 300 dpi because it better fits the use case of copying a selection to a document intended for print, like in Word or LibreOffice Writer for example.
(And sorry, I just realized the first two commits overlap with #1814. Still getting the hang of juggling multiple Git branches.)

Always use PNG for copy to image (#1811)

---

frescobaldi_app/appinfo.py
frescobaldi_app/lilydoc/manager.py
frescobaldi_app/lilypondinfo.py

This helps when users are running an older version of LilyPond that doesn't include local documentation.

Prefer remote docs for the user's default LilyPond version

---

CHANGELOG.md
frescobaldi_app/appinfo.py
linux/org.frescobaldi.Frescobaldi.metainfo.xml.in
pyproject.toml

I put a release date (20th of January) in the Changelog just because I had to. We'll see when we manage to do it really.

Version 4.0.0: bump version and update the Changelog

---

linux/org.frescobaldi.Frescobaldi.metainfo.xml.in
tox.ini

appstream-util validation is currently failing even if the metainfo file is correct.
Let's switch to appstreamcli, which is actively maintained and it's the tool used by Flathub...

Switch to appstreamcli validate

---

i18n/po-update.py

Fixes #1871
In my previous PR I missed that the script on line 54 used a quoted string instead of the variable defined at the beginning. So in this PR I preferred giving a new name to this variable and use it consistently.

Use the new directory name to extract translatable strings

---

frescobaldi/scorewiz/build.py
frescobaldi/scorewiz/parts/_base.py
frescobaldi/scorewiz/parts/brass.py
frescobaldi/scorewiz/parts/containers.py
frescobaldi/scorewiz/parts/keyboard.py
frescobaldi/scorewiz/parts/percussion.py
frescobaldi/scorewiz/parts/plucked_strings.py
frescobaldi/scorewiz/parts/special.py
frescobaldi/scorewiz/parts/strings.py
frescobaldi/scorewiz/parts/woodwind.py
frescobaldi/scorewiz/settings.py

This PR includes several Score Wizard improvements that I'd postponed to focus on finishing the Qt 6 port. Most notably, it reworks the handling of transposing instruments as discussed under #1733 and #1800.
It also adds a couple new instrument types, fixes a few bugs, and standardizes spelling and punctuation of instrument names.

Score Wizard improvements, Qt 6 edition

---

frescobaldi/debuginfo.py
frescobaldi/install/update.py
frescobaldi/musicview/__init__.py
frescobaldi/musicview/contextmenu.py
frescobaldi/musicview/pointandclick.py
frescobaldi/pagedview.py
frescobaldi/preferences/musicviewers.py
frescobaldi/userguide/prefs_musicviewers.md
frescobaldi/viewers/__init__.py
frescobaldi/viewers/abstractviewwidget.py
frescobaldi/viewers/manuscript/widget.py
frescobaldi/viewers/pdfwidget.py
frescobaldi/viewers/pointandclick.py
frescobaldi/viewers/popplerwidget.py

This includes minor features like manually selecting a rendering backend or printing directly to CUPS. It also updates outdated references to Poppler in several comments and docstrings, and fully removes debugging information about the Poppler version that was previously commented out.
Removing these would allow us to completely drop Poppler support in qpageview as discussed under frescobaldi/qpageview#32.

Remove remaining pieces that depend on Poppler

---

frescobaldi/preferences/import_export.py
frescobaldi/textformats.py

When in Windows, the default font is now Consolas.  Fixes issue #1894

Change default font in Windows, fixes issue #1894

---

pyproject.toml

Fixes #1898 
`tox -e mo-generate` can be called from pyproject.toml?
I've built the wheel with `python -m build` and then installed it. Languages and user manuals are available.
Please review as I don't know Python packaging best practices.

Add package data files to be included or excluded

---

CHANGELOG.md
frescobaldi/appinfo.py
linux/org.frescobaldi.Frescobaldi.metainfo.xml.in
pyproject.toml

Bumping to a new .dev version right after a release will help us to easily distinguish an unreleased version.
Consider that we may ask users to install a package built from an open PR.
When we make the release we simply remove the .dev1 extension.

Bump to version 4.0.1.dev1

---

frescobaldi/midiinput/elements.py

Fixes issue #1916
@bmjcode I found this bug while preparing a patch for the user manual. I want to add some instructions for MIDI playback and MIDI input.
I see that there are other `Qt.Modifier` uses in the code that should be probably modified? I'm not confident with Qt and programming in general...
```
git grep -n 'Qt\.Modifier' frescobaldi/
[...]
```
https://doc.qt.io/qt-6/qt.html#KeyboardModifier-enum

Use Qt6 enums in MIDI input

---

frescobaldi/mainwindow.py

Adding a widget to a layout [changes its parent](https://doc.qt.io/qt-6/layout.html#tips-for-using-layouts) to the widget on which the layout is installed. Here the layout is on `self.mainwidget`, and the tab bar and view manager become its children. Thus if `mainwidget` is a local variable, the tab bar and view manager are garbage-collected when the constructor returns and `mainwidget` goes out of scope, even though they were constructed with the `MainWindow` instance as their parent.
Hopefully this finally fixes the infamous https://github.com/frescobaldi/frescobaldi/issues/1467.

Make mainwidget an instance attribute so it's not garbage-collected

---

frescobaldi/musicpos.py
frescobaldi/signals.py

This fixes instances of #1467 where a PyQt object's underlying C++ object is deleted before the Python object is garbage-collected.

Block further method calls if we encounter a RuntimeError

---

frescobaldi/signals.py

Fix "TypeError: 'NoneType' object is not callable" in signals.py

---

frescobaldi/preferences/musicviewers.py

This fixes a UI bug where no default is shown for those preferences on a clean installation.

Set default preference values for page scaling and scrolling orientation

---

frescobaldi/fonts/oldfontsdialog.py

Yet another overseen Qt6 change.
Fix issue #1954

QFontComboBox does not have a FontDialogOption attribute

---

frescobaldi/mainwindow.py

GNOME and Windows¹ do not have a standard keyboard shortcut to open the Preferences so there's no default shortcut in these platforms. We can force Ctrl+, which is the default on macOS but it's also very common on some popular crossplatform editors.
This is a partial fix for #887
¹ https://doc.qt.io/qt-6/qkeysequence.html#standard-shortcuts

Add Ctrl+, shortcut to open the Preferences

---

frescobaldi/appinfo.py
frescobaldi/checks.py

If Qt version is below the required version (currently 6.6), the following error window will appear:
and the user will be forced to quit Frescobaldi.

Add Qt version check

---

frescobaldi/historymanager.py

This fixes `ValueError: list.remove(x): x not in list` as reported in multiple issues (#1324, #1914, #1972, and many duplicates).

Make removeDocument() fail safely if there is no document to remove

---

pyproject.toml

This fork re-enables MIDI output on macOS.
Fix #1946

Use Pygame Community Edition

---

frescobaldi/hyphenator.py
frescobaldi/install/update.py

Since Python 3 is now required, these constitute dead execution branches.

delete Python 2 compatibility measures

---

frescobaldi/exception.py

Trivial change, but let's hope it will encourage users to write what they think might have triggered the bug.
As discussed [here](https://github.com/frescobaldi/frescobaldi/issues/2008#issuecomment-2989167087).

Bug reports: ask the user to explain what he was doing

---

frescobaldi/signals.py

Fix two instances of bare excepts:
$ ruff check --select E722
All checks passed!

Fix ruff E722, no bare excepts

---

INSTALL.md

I added a section in INSTALL.md for non-technical Linux users who are downloading the compressed tar file in the release website.  Fixes #2026

Add installation instructions for non-technical Linux users

---

frescobaldi/miditool/widget.py
frescobaldi/qmidi/player.py

This avoids multiple players blocking one another's access to MIDI ports.
Fixes #2041.

Make all MIDI widgets share a single player instance

---

frescobaldi/autocomplete/analyzer.py
frescobaldi/extensions/__init__.py
frescobaldi/extensions/panel.py
frescobaldi/job/lilypond.py
frescobaldi/pitch/pitch.py
frescobaldi/preferences/general.py
frescobaldi/sessions/__init__.py
frescobaldi/sessions/dialog.py
frescobaldi/viewers/contextmenu.py
frescobaldi/viewers/toolbar.py
frescobaldi/vimode/__init__.py
frescobaldi/widgets/folding.py

These are modifications to fix `ruff check --select F841`, unused variables.  There are still two outstanding warnings, but those are complex enough that I think they deserve their own PR.

Modifications to remove unused variables

---

CHANGELOG.md
frescobaldi/appinfo.py
linux/org.frescobaldi.Frescobaldi.metainfo.xml.in
pyproject.toml

File associations should now work fine on Windows
and macOS since briefcase version 0.3.24.
This is currently a draft. I want other open PRs to be merged before making the release. The target date is Tuesday 29th of July.

4.0.4 release

---

frescobaldi/debug.py
frescobaldi/documenttooltip.py
frescobaldi/externalchanges/widget.py
frescobaldi/scorewiz/parts/__init__.py
frescobaldi/snippet/insert.py
frescobaldi/snippet/model.py
frescobaldi/vcs/menu.py

Modifications have been made so that the ruff linter warnings for "redefined while used" (F811) are gone.
$ ruff check --select F811
All checks passed!
There were two instances where the code took this form:
def foo():
f = Bar()
global foo
foo = lambda: f
return f
I'm assuming this is a Pythonic way to create a singleton and I marked the code so that ruff would skip the checks on those.  I don't know of a way to create a singleton in Python that ruff will pass.

Modifications to fix ruff warnings, redefined while unused (F811)

---

.github/workflows/release.yml

Python 3.13 is mature and it's what I've been using for months on Linux and Windows.
Let's use it to build the Windows and macOS packages.

Use Python 3.13 in GitHub Actions workflow
